# Generated by Django 6.1.1 on 2026-09-29 03:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Área')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Área de Conocimiento',
                'verbose_name_plural': 'Áreas de Conocimiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('COORDINADOR', 'Coordinador Académico')], default='ESTUDIANTE', help_text='Define si el usuario es Estudiante o Coordinador Académico', max_length=20, verbose_name='Rol en la Plataforma')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CarroMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carro', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante Titular')),
            ],
            options={
                'verbose_name': 'Carro de Matrícula',
                'verbose_name_plural': 'Carros de Matrícula',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Curso/Bootcamp')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('costo_matricula', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de Matrícula (CLP)')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(verbose_name='Fecha de Término')),
                ('cupos_maximos', models.PositiveIntegerField(verbose_name='Cupos Máximos')),
                ('cupos_disponibles', models.PositiveIntegerField(verbose_name='Cupos Disponibles')),
                ('activo', models.BooleanField(default=True, verbose_name='Curso Activo')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='academico.areaconocimiento', verbose_name='Área de Conocimiento')),
            ],
            options={
                'verbose_name': 'Curso / Bootcamp',
                'verbose_name_plural': 'Cursos y Bootcamps',
                'ordering': ['fecha_inicio', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='PAGADO', max_length=20, verbose_name='Estado de la Matrícula')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Total (CLP)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante Matriculado')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_historico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Histórico (CLP)')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_matricula', to='academico.curso', verbose_name='Curso')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='academico.matricula', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Detalle de Matrícula',
                'verbose_name_plural': 'Detalles de Matrícula',
            },
        ),
        migrations.CreateModel(
            name='ItemCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Agregado')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academico.carromatricula', verbose_name='Carro Asociado')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_carros', to='academico.curso', verbose_name='Curso Seleccionado')),
            ],
            options={
                'verbose_name': 'Ítem de Carro',
                'verbose_name_plural': 'Ítems de Carro',
                'ordering': ['-fecha_agregado'],
                'unique_together': {('carro', 'curso')},
            },
        ),
    ]
