# Generated by Django 6.1.1 on 2026-09-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cantidad_computadores',
            field=models.PositiveIntegerField(default=20, verbose_name='Cantidad de Computadores'),
        ),
        migrations.AddField(
            model_name='curso',
            name='laboratorio',
            field=models.CharField(default='Laboratorio TI-1', max_length=100, verbose_name='Laboratorio Asignado'),
        ),
    ]
