# Generated by Django 6.1 on 2026-09-30 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_curso_cantidad_computadores_curso_laboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_anuladas', to=settings.AUTH_USER_MODEL, verbose_name='Anulado por'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Anulación'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Anulación'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='estado',
            field=models.CharField(choices=[('PAGADO', 'Pagado'), ('ANULADA', 'Anulada')], default='PAGADO', max_length=20, verbose_name='Estado de la Matrícula'),
        ),
    ]
