# Generated by Django 6.1 on 2026-09-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_matricula_anulado_por_matricula_fecha_anulacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fecha_desactivacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Desactivación'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Programa Activo'),
        ),
    ]
